### ISSUE TITLE
RFE: jo x=1 x=2 to create lists

### ISSUE THREAD

**Issue by gdamjan** [jpmens/jo#176] opened 2022-04-14 09:50 UTC
The current behavior of repeated keys creates a useless json:
```
$ jo x=1 x=2
{"x":1,"x":2}
```

maybe this can be reused to create lists, like:
```
$ jo x=1 x=2
{"x":[1, 2]}
```
if it doesn't break something in the current behavior.

**Comment by PicoMitchell** [comment] 2022-05-04 16:43
That could lead to confusing/ambiguous results if someone were to use the `-D` option to "deduplicate object keys" especially if they were intending to create an array with some duplicate keys but ignore duplicate keys for other values in the same invocation.

```
% jo -D x=1 x=2
{"x":2}
```

If someone wants an array, they can just do `jo 'x[]=1' 'x[]=2'` which will also work as intended if `-D `is also used for other keys/values.

**Comment by jpmens** [comment] 2022-08-31 17:48
I don't think we'll address this now.
Closing.

**Closed by jpmens** 2022-08-31 17:48 UTC
